name: Deploy to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_REPOSITORY: harshbhardwaj7/wisecow
  EKS_CLUSTER_NAME: wisecow-demo
  AWS_REGION: us-east-1

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: harshbhardwaj7/wisecow
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }} 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_REGION}}
    
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Update kube config
      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

    - name: Deploy to EKS
      env:
        DOCKER_REPOSITORY: ${{ env.DOCKER_REPOSITORY }}        
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i.bak "s|DOCKER_IMAGE|$DOCKER_REPOSITORY:$IMAGE_TAG|g" K8s/deployment.yaml && \
        kubectl apply -f K8s/deployment.yaml
        kubectl apply -f K8s/service.yaml
        kubectl apply -f K8s/cert-manager.yaml
        kubectl apply -f K8s/clusterissuer.yaml
        kubectl apply -f K8s/certificate.yaml
        kubectl apply -f K8s/ingress.yaml
